//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduler.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scheduler.Common.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string AuditableCreatedByName {
            get {
                return ResourceManager.GetString("AuditableCreatedByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string AuditableCreatedByShortName {
            get {
                return ResourceManager.GetString("AuditableCreatedByShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created On.
        /// </summary>
        public static string AuditableCreatedName {
            get {
                return ResourceManager.GetString("AuditableCreatedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created On.
        /// </summary>
        public static string AuditableCreatedShortName {
            get {
                return ResourceManager.GetString("AuditableCreatedShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated By.
        /// </summary>
        public static string AuditableLastUpdatedByName {
            get {
                return ResourceManager.GetString("AuditableLastUpdatedByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated By.
        /// </summary>
        public static string AuditableLastUpdatedByShortName {
            get {
                return ResourceManager.GetString("AuditableLastUpdatedByShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated On.
        /// </summary>
        public static string AuditableLastUpdatedName {
            get {
                return ResourceManager.GetString("AuditableLastUpdatedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated On.
        /// </summary>
        public static string AuditableLastUpdatedShortName {
            get {
                return ResourceManager.GetString("AuditableLastUpdatedShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Port.
        /// </summary>
        public static string ClientAgentPortName {
            get {
                return ResourceManager.GetString("ClientAgentPortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Port.
        /// </summary>
        public static string ClientAgentPortShortName {
            get {
                return ResourceManager.GetString("ClientAgentPortShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Virtual Directory.
        /// </summary>
        public static string ClientAgentVirtualDirectoryName {
            get {
                return ResourceManager.GetString("ClientAgentVirtualDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Virtual Dir.
        /// </summary>
        public static string ClientAgentVirtualDirectoryShortName {
            get {
                return ResourceManager.GetString("ClientAgentVirtualDirectoryShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ClientDescriptionName {
            get {
                return ResourceManager.GetString("ClientDescriptionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ClientDescriptionShortName {
            get {
                return ResourceManager.GetString("ClientDescriptionShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Name.
        /// </summary>
        public static string ClientNetworkNameName {
            get {
                return ResourceManager.GetString("ClientNetworkNameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Name.
        /// </summary>
        public static string ClientNetworkNameShortName {
            get {
                return ResourceManager.GetString("ClientNetworkNameShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console Output.
        /// </summary>
        public static string LogEntryConsoleOutName {
            get {
                return ResourceManager.GetString("LogEntryConsoleOutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string LogEntryConsoleOutShortName {
            get {
                return ResourceManager.GetString("LogEntryConsoleOutShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Output.
        /// </summary>
        public static string LogEntryErrorOutName {
            get {
                return ResourceManager.GetString("LogEntryErrorOutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string LogEntryErrorOutShortName {
            get {
                return ResourceManager.GetString("LogEntryErrorOutShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Code.
        /// </summary>
        public static string LogEntryExitCodeName {
            get {
                return ResourceManager.GetString("LogEntryExitCodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Code.
        /// </summary>
        public static string LogEntryExitCodeShortName {
            get {
                return ResourceManager.GetString("LogEntryExitCodeShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished At.
        /// </summary>
        public static string LogEntryFinishedName {
            get {
                return ResourceManager.GetString("LogEntryFinishedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished At.
        /// </summary>
        public static string LogEntryFinishedShortName {
            get {
                return ResourceManager.GetString("LogEntryFinishedShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forced Execution.
        /// </summary>
        public static string LogEntryForcedName {
            get {
                return ResourceManager.GetString("LogEntryForcedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forced.
        /// </summary>
        public static string LogEntryForcedShortName {
            get {
                return ResourceManager.GetString("LogEntryForcedShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process ID.
        /// </summary>
        public static string LogEntryProcessIdName {
            get {
                return ResourceManager.GetString("LogEntryProcessIdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PID.
        /// </summary>
        public static string LogEntryProcessIdShortName {
            get {
                return ResourceManager.GetString("LogEntryProcessIdShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shell Command.
        /// </summary>
        public static string LogEntryShellCommandName {
            get {
                return ResourceManager.GetString("LogEntryShellCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        public static string LogEntryShellCommandShortName {
            get {
                return ResourceManager.GetString("LogEntryShellCommandShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started At.
        /// </summary>
        public static string LogEntryStartedName {
            get {
                return ResourceManager.GetString("LogEntryStartedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started At.
        /// </summary>
        public static string LogEntryStartedShortName {
            get {
                return ResourceManager.GetString("LogEntryStartedShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Directory.
        /// </summary>
        public static string LogEntryWorkingDirectoryName {
            get {
                return ResourceManager.GetString("LogEntryWorkingDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        public static string LogEntryWorkingDirectoryShortName {
            get {
                return ResourceManager.GetString("LogEntryWorkingDirectoryShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cron Expression.
        /// </summary>
        public static string ScheduleEntryCronExpressionName {
            get {
                return ResourceManager.GetString("ScheduleEntryCronExpressionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid cron expression..
        /// </summary>
        public static string ScheduleEntryCronExpressionRegex {
            get {
                return ResourceManager.GetString("ScheduleEntryCronExpressionRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cron.
        /// </summary>
        public static string ScheduleEntryCronExpressionShortName {
            get {
                return ResourceManager.GetString("ScheduleEntryCronExpressionShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string ScheduleEntryEnabledName {
            get {
                return ResourceManager.GetString("ScheduleEntryEnabledName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string ScheduleEntryEnabledShortName {
            get {
                return ResourceManager.GetString("ScheduleEntryEnabledShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shell Command.
        /// </summary>
        public static string ScheduleEntryShellCommandName {
            get {
                return ResourceManager.GetString("ScheduleEntryShellCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        public static string ScheduleEntryShellCommandShortName {
            get {
                return ResourceManager.GetString("ScheduleEntryShellCommandShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Directory.
        /// </summary>
        public static string ScheduleEntryWorkingDirectoryName {
            get {
                return ResourceManager.GetString("ScheduleEntryWorkingDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        public static string ScheduleEntryWorkingDirectoryShortName {
            get {
                return ResourceManager.GetString("ScheduleEntryWorkingDirectoryShortName", resourceCulture);
            }
        }
    }
}
